<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Wytwórnia')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/layout.css'))  ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar main-navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand layout-brand" href="<?php echo $this->url('home') ?>"><img id="logo" src="<?php echo $this->basePath('img/winyl logo.jpg') ?>" alt="Wytwornia"/><span>&nbsp;<?php echo 'Wytwórnia płytowa' ?></span></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-menu">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class=""><a href="<?php echo $this->url('about', array(), array('force_canonical' => true)) ?>"><?php echo 'About' ?></a></li>
                        <li class=""><a href="<?php echo $this->url('artist', array(), array('force_canonical' => true)) ?>"><?php echo 'Artists' ?></a></li>
                        <li class=""><a href="<//?php echo $this->url('contact', array(), array('force_canonical' => true)) ?>"><?php echo 'Contact' ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <footer>
                <div class="container footer-container">
                    <div class="col-lg-3 footer-row">
                        <h3><?php echo 'Site map' ?></h3>
                        <ul>
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li><a href="<?php echo $this->url('about', array(), array('force_canonical' => true)) ?>"><?php echo 'About' ?></a></li>
                            <li><a href="<?php echo $this->url('artist', array(), array('force_canonical' => true)) ?>"><?php echo 'Artists' ?></a></li>
                            <li><a href="<//?php echo $this->url('contact', array(), array('force_canonical' => true)) ?>"><?php echo 'Contact' ?></a></li>
                        </ul>  
                    </div>
                    <div id='rights'>
                        <p>&copy;<?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                    </div>
                </div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
