-- MySQL Script generated by MySQL Workbench
-- 03/23/15 11:14:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(30) NULL,
  `Login` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Privilages` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Band`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Band` (
  `idBand` INT NOT NULL,
  `BandName` VARCHAR(45) NULL,
  `Description` VARCHAR(1000) NULL,
  `Avarage` INT NULL,
  PRIMARY KEY (`idBand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disc` (
  `idDisc` INT NOT NULL,
  `DiscName` VARCHAR(45) NULL,
  `Year` DATE NULL,
  `Description` VARCHAR(1000) NULL,
  `Band_idBand` INT NOT NULL,
  PRIMARY KEY (`idDisc`),
  INDEX `fk_Disc_Band1_idx` (`Band_idBand` ASC),
  CONSTRAINT `fk_Disc_Band1`
    FOREIGN KEY (`Band_idBand`)
    REFERENCES `mydb`.`Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Song` (
  `idSong` INT NOT NULL,
  `SangName` VARCHAR(45) NULL,
  `duration` TIME(20) NULL,
  `Disc_idDisc` INT NOT NULL,
  PRIMARY KEY (`idSong`),
  INDEX `fk_Song_Disc1_idx` (`Disc_idDisc` ASC),
  CONSTRAINT `fk_Song_Disc1`
    FOREIGN KEY (`Disc_idDisc`)
    REFERENCES `mydb`.`Disc` (`idDisc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rate` (
  `idRates` INT NOT NULL,
  `Rate` INT(10) NULL,
  `User_idUser` INT NOT NULL,
  `Song_idSong` INT NOT NULL,
  PRIMARY KEY (`idRates`),
  INDEX `fk_Rate_User_idx` (`User_idUser` ASC),
  INDEX `fk_Rate_Song1_idx` (`Song_idSong` ASC),
  CONSTRAINT `fk_Rate_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rate_Song1`
    FOREIGN KEY (`Song_idSong`)
    REFERENCES `mydb`.`Song` (`idSong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `idComment` INT UNSIGNED NOT NULL,
  `Comment` VARCHAR(50) NULL,
  `User_idUser` INT NOT NULL,
  `Band_idBand` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `fk_Comment_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Comment_Band1_idx` (`Band_idBand` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Band1`
    FOREIGN KEY (`Band_idBand`)
    REFERENCES `mydb`.`Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
