-- MySQL Script generated by MySQL Workbench
-- 04/20/15 11:40:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wytwornia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wytwornia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wytwornia` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wytwornia` ;

-- -----------------------------------------------------
-- Table `wytwornia`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Comment` (
  `idComment` INT NOT NULL,
  `comment` VARCHAR(1000) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `fk_Comment_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Comment_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `wytwornia`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Artist` (
  `idArtist` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `description` VARCHAR(1000) NULL,
  `short_text` VARCHAR(45) NULL,
  `average` DOUBLE NULL,
  `Comment_idComment` INT NOT NULL,
  PRIMARY KEY (`idArtist`),
  INDEX `fk_Artist_Comment1_idx` (`Comment_idComment` ASC),
  CONSTRAINT `fk_Artist_Comment1`
    FOREIGN KEY (`Comment_idComment`)
    REFERENCES `wytwornia`.`Comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Album` (
  `idAlbum` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `date` DATE NULL,
  `description` VARCHAR(1000) NULL,
  `Artist_idArtist` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  INDEX `fk_Album_Artist1_idx` (`Artist_idArtist` ASC),
  CONSTRAINT `fk_Album_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `wytwornia`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Song` (
  `idSong` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `songWriter` VARCHAR(45) NULL,
  `composer` VARCHAR(45) NULL,
  `duration` TIME(6) NULL,
  `Album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idSong`),
  INDEX `fk_Song_Album1_idx` (`Album_idAlbum` ASC),
  CONSTRAINT `fk_Song_Album1`
    FOREIGN KEY (`Album_idAlbum`)
    REFERENCES `wytwornia`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Rate` (
  `idRate` INT NOT NULL,
  `rate` INT NULL,
  `Song_idSong` INT NOT NULL,
  PRIMARY KEY (`idRate`),
  INDEX `fk_Rate_Song1_idx` (`Song_idSong` ASC),
  CONSTRAINT `fk_Rate_Song1`
    FOREIGN KEY (`Song_idSong`)
    REFERENCES `wytwornia`.`Song` (`idSong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`User` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `date` DATE NULL,
  `privilages` TINYINT(1) NULL,
  `Rate_idRate` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Rate1_idx` (`Rate_idRate` ASC),
  CONSTRAINT `fk_User_Rate1`
    FOREIGN KEY (`Rate_idRate`)
    REFERENCES `wytwornia`.`Rate` (`idRate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`News` (
  `idNews` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(2000) NULL,
  `Artist_idArtist` INT NOT NULL,
  PRIMARY KEY (`idNews`),
  INDEX `fk_News_Artist1_idx` (`Artist_idArtist` ASC),
  CONSTRAINT `fk_News_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `wytwornia`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
