-- MySQL Script generated by MySQL Workbench
-- 04/13/15 15:23:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wytwornia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wytwornia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wytwornia` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wytwornia` ;

-- -----------------------------------------------------
-- Table `wytwornia`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(30) NULL,
  `Login` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Privilages` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Artist` (
  `idArtist` INT NOT NULL,
  `ArtistName` VARCHAR(45) NULL,
  `Description` VARCHAR(1000) NULL,
  `Avarage` INT NULL,
  `ShortText` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Album` (
  `idAlbum` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Description` VARCHAR(1000) NULL,
  `Band_idBand` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  INDEX `fk_Disc_Band1_idx` (`Band_idBand` ASC),
  CONSTRAINT `fk_Disc_Band1`
    FOREIGN KEY (`Band_idBand`)
    REFERENCES `wytwornia`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Song` (
  `idSong` INT NOT NULL,
  `SangName` VARCHAR(45) NULL,
  `duration` TIME(6) NULL,
  `Disc_idDisc` INT NOT NULL,
  PRIMARY KEY (`idSong`),
  INDEX `fk_Song_Disc1_idx` (`Disc_idDisc` ASC),
  CONSTRAINT `fk_Song_Disc1`
    FOREIGN KEY (`Disc_idDisc`)
    REFERENCES `wytwornia`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Rate` (
  `idRates` INT NOT NULL,
  `Rate` INT(10) NULL,
  `User_idUser` INT NOT NULL,
  `Song_idSong` INT NOT NULL,
  PRIMARY KEY (`idRates`),
  INDEX `fk_Rate_User_idx` (`User_idUser` ASC),
  INDEX `fk_Rate_Song1_idx` (`Song_idSong` ASC),
  CONSTRAINT `fk_Rate_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `wytwornia`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rate_Song1`
    FOREIGN KEY (`Song_idSong`)
    REFERENCES `wytwornia`.`Song` (`idSong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wytwornia`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wytwornia`.`Comment` (
  `idComment` INT UNSIGNED NOT NULL,
  `Comment` VARCHAR(50) NULL,
  `User_idUser` INT NOT NULL,
  `Band_idBand` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `fk_Comment_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Comment_Band1_idx` (`Band_idBand` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `wytwornia`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Band1`
    FOREIGN KEY (`Band_idBand`)
    REFERENCES `wytwornia`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
