<div class='col-lg-12 carousel_col'>
    <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel" data-slide-to="0" class="active"></li>
        <li data-target="#carousel" data-slide-to="1"></li>
        <li data-target="#carousel" data-slide-to="2"></li>
      </ol>
      <!-- Carousel items -->
      <div class="carousel-inner">
        <div class="active item"><img src="http://www.planetarygroup.com/wp-content/uploads/2014/04/best-albums-compsq_wide-fdb5b7184b19dcdc1a0874b219dee219679268c2-s6-c30.jpg" alt='album1'></div>
        <div class="item"><img src='https://tctechcrunch2011.files.wordpress.com/2008/01/albumcovers.jpg' alt='album2'></div>
        <div class="item"><img src='http://www.impalamusic.org/sites/default/files/pictures/Web%20banner%20Album%20of%20the%20Year%202014.png' alt='album3'></div>
      </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">News</h3>
            </div>
            <div class="panel-body">
                <b>FAITH NO MORE</b> can now announce a couple of UK headline dates that will be directly following their Saturday main stage appearance at Download Festival.

                These dates are:
                June 14 - Glasgow, UK ' O2 Academy 
                June 17 - London, UK ' Roundhouse

                Pre-sale (live nation & artist) will be on Wednesday 15th April at 10am, with general on sale Friday 17th April 10am.
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Artist</h3>
            </div>
            <div class="panel-body">
                <b>Arctic Monkeys</b> are an English rock band formed in 2002 in High Green, a suburb of Sheffield. The band consists of Alex Turner (lead vocals, rhythm guitar, lead guitar), Jamie Cook (lead guitar, rhythm guitar), Nick O'Malley (bass, backing vocals), and Matt Helders (drums, backing vocals). Former band member Andy Nicholson (bass guitar, backing vocals) left the band in 2006 shortly after their debut album was released ...
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">News</h3>
            </div>
            <div class="panel-body">
                <b>Hozier's </b>teenage years "colour the lens" he looks through today.

                The Irish musician's hit track Take Me to Church reached the number one spot in a dozen countries following its release last year, with his debut self-titled album also making an impact in the charts.

                Full of heart-felt and intense lyrics, Hozier has recalled the years which turned him into the musical star he is today ...
            </div>
        </div>
    </div>
</div>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/main-page.css')) ?>
<?php echo $this->headScript()
            ->prependFile($this->basePath('js/main-page.js'));   ?>